// Program 6_8
// Generating multiple random numbers
#include <iostream>
#include <cstdlib>
using namespace std;

int main() {
	int x = rand();
	cout << "The random number is " << x << endl;
	cout << "Here is another random number: " << rand() << endl;
	cout << "... and another: " << rand() << endl;                                      
}

// these are pseudo-random numbers, because they are generated by a deterministic process.
// The rand() function generates a pseudo-random number between 0 and RAND_MAX.
// The value of RAND_MAX is implementation-defined, but it is guaranteed to be at least 32767.