// Program 6_7
// Random Number generation example
#include <iostream>
#include <cstdlib> // This header file is included to use the standard library functions for random number generation.
using namespace std;

int main() {
	int x = rand();
	cout << "The random number is " << x << endl;                                               
}


// random number generation is the process of generating a sequence of numbers that cannot be reasonably predicted better than by random chance.
// Random numbers are often used in simulations, cryptography, and other applications where unpredictability is important.
// what we are actually doing is generating a pseudo-random number.
// A pseudo-random number is a number that appears to be random but is generated by a deterministic process.
// Pseudo-random numbers are generated using algorithms that produce a sequence of numbers that have properties similar to those of random numbers.
// The rand() function is a standard C++ library function that generates pseudo-random numbers.