3.33.1.
#include <stdio.h>
#include <memory.h> #define TRUE 1 #define FALSE 0 #define DEFAULT_INPUTFILE "sudoku1.txt" typedef int TTable[9][9];
void ReadTable(FILE * fd, TTable T) { int i, j;
for (i = 0;
i < 9;
i++) { for (j = 0;
j < 9;
j++) fscanf(fd, "%d", &T[i][j]);
} } void PrintTable(TTable T) { int i, j;
for (i = 0;
i < 9;
i++) { for (j = 0;
j < 9;
j++) printf("%d ", T[i][j]);
printf("\n");
} } int CheckRowsColumns(TTable T) { int i, j, n, num;
for (i = 0;
i < 9;
i++) { for (j = 0;
j < 9;
j++) { n = i ? 0 : 1;
num = T[i][j];
while ((n < 9) && (T[n][j] != num)) n += (i == n + 1) ? 2 : 1;
if (n < 9) { printf("This is a wrong table!\n");
return FALSE;
} n = j ? 0 : 1;
num = T[i][j];
while ((n < 9) && (T[i][n] != num)) n += (j == n + 1) ? 2 : 1;
if (n < 9) { printf("This is a wrong table!\n");
return FALSE;
} } } } return TRUE;
int CheckOneCell(TTable T, int x, int y) { int i, j, num, err;
for (num = 1;
num <= 9;
num++) { err = TRUE;
for (i = y * 3;
i < (y + 1) * 3;
i++) { for (j = x * 3;
j < (x + 1) * 3;
j++) { if (T[i][j] == num) err = FALSE;
} } if (err) { printf("This is a wrong table!\n");
return FALSE;
} } return TRUE;
} void CheckCells(TTable T) { int i, j;
for (i = 0;
i < 3;
i++) for (j = 0;
j < 3;
j++) if (!CheckOneCell(T, i, j)) return;
printf("This table is correct!\n");
} void Check(TTable T) { if (CheckRowsColumns(T)) CheckCells(T);
} int main(int argc, char * argv[]) { TTable Table;
FILE * fd = fopen(argc > 1 ? argv[1] : DEFAULT_INPUTFILE, "r");
if (fd == NULL) { perror("Error");
return 0;
} ReadTable(fd, Table);
fclose(fd);
PrintTable(Table);
Check(Table);
return 0;
} 
3.33.1. Írjon programot, amely leellenőriz egy kitöltött Sudoku táblát! A tábla értékeit olvassa be fájlból! Egy tábla akkor van helyesen kitöltve, ha minden sorban, minden oszlopban és minden kis 3x3-as kis négyzetben az 1-9 közti számjegyek mindegyike egyszer szerepel. Az ábrán egy helyesen kitöltött tábla szerepel. 9 5 8 2 7 4 6 3 1 1 4 7 5 3 6 9 2 8 2 6 3 9 8 1 4 7 5 8 3 1 4 6 9 2 5 7 4 2 5 3 1 7 8 9 6 7 9 6 8 5 2 1 4 3 3 1 4 7 2 8 5 6 9 5 8 9 6 4 3 7 1 2 6 7 2 1 9 5 3 8 4 Ábra: Sudoku tábla Az input fájl formátuma: Az input fájl 9 sort és 9 oszlopot tartalmaz. A számjegyek egy-egy szóköz karakterrel vannak elválasztva. Példa bemenet: 7 4 6 8 3 1 5 9 2 9 2 3 5 7 4 8 6 1 8 1 5 2 9 6 4 7 3 1 3 4 7 5 2 6 8 9 6 9 7 3 1 8 2 5 4 5 8 2 4 6 9 1 3 7 4 7 9 6 2 8 3 1 8 3 6 8 1 4 7 9 2 5 2 5 1 9 8 3 7 4 6 Kimenet: This is a wrong table! 3.34. Amőba játék
