3.37.1.
#include <stdio.h>
#include <stdlib.h> #define DEFAULT_INPUTFILE "matrices1.txt" struct TMatrix { int r,c;
int ** m;
};
void InitMatrix(struct TMatrix * M, int r, int c) { int i,j;
M->r = r;
M->c = c;
M->m = (int**)malloc(sizeof(int*) * r);
for (i = 0;
i < r;
i++) { M->m[i] = (int*)malloc(sizeof(int) * c);
for (j = 0;
j < c;
j++) M->m[i][j] = 0;
} } void FreeMatrix(struct TMatrix * M) { int i;
for (i = 0;
i < M->r;
i++) { free(M->m[i]);
M->m[i] = NULL;
} free(M->m);
M->m = NULL;
M->r = M-> c = 0;
} void PrintMatrix(struct TMatrix * M) { int i, j;
for (i = 0;
i < M->r;
i++) { for (j = 0;
j < M->c;
j++) printf("%3d ", M->m[i][j]);
printf("\n\n\n");
} } void ReadMatrix(FILE * fd, struct TMatrix * M) { } int i, j;
for (i = 0;
i < M->r;
i++) { for (j = 0;
j < M->c;
j++) fscanf(fd, "%d", &M->m[i][j]);
} void AddMulMatrix(struct TMatrix * A, struct TMatrix * B, struct TMatrix * C, int m) { int i, j;
for (i = 0;
i < A->r;
i++) { for (j = 0;
j < A->c;
j++) C->m[i][j] = (A->m[i][j] + B->m[i][j]) * m;
} } int main(int argc, char *argv[]) { struct TMatrix A, B, C;
int r, c;
FILE * fd = fopen( argc > 1 ? argv[1] : DEFAULT_INPUTFILE, "r");
if (fd == NULL) { perror("Error");
return 0;
} fscanf(fd, "%d %d", &r, &c);
InitMatrix(&A, r, c);
InitMatrix(&B, r, c);
InitMatrix(&C, r, c);
ReadMatrix(fd, &A);
ReadMatrix(fd, &B);
fclose(fd);
printf("A : \n\n");
PrintMatrix(&A);
printf("B : \n\n");
PrintMatrix(&B);
AddMulMatrix(&A, &B, &C, 2);
printf("************************\n (A + B) * 2 = \n\n");
PrintMatrix(&C);
FreeMatrix(&A);
FreeMatrix(&B);
FreeMatrix(&C);
return 0;
} 
3.37.1. Írjon programot mátrixösszeadás és skalárral való szorzás megvalósítására! A program olvassa be fájlból két mátrixot! Adja össze a két mátrixot, és az eredményt szorozza meg 2-vel! A mátrixokat dinamikusan hozza létre! Ha A, B és C azonos méretű mátrixok, akkor Cij = Aij + Bij , ahol C az A és B mátrixok összege. Egy mátrix „d” skalárral való szorzásakor a mátrix minden elemét „d”-vel szorozzuk. Az input fájl formátuma: Első sor: Két szám, az első a sorok, a második az oszlopok száma. A többi sorban a két mátrix található, a példában látható módon. Minden sorban egy-egy mátrix-sor van, a számok szóköz karakterekkel vannak elválasztva. A mátrixok elemei egész számok. Példa bemenet: 2 3 4 3 4 3 1 5 2 4 1 1 7 3 Kimenet: A : 4 3 4 3 1 5 B : 2 4 1 1 7 3 ************************ (A + B) * 2 = 12 14 10 8 16 16 3.38. Morze kód
